---

- name: Install Python PIP (Python Package Installer)
  apt:
    name: python-pip
    state: present

- name: Install Docker python handler
  pip:
    name: docker-py
    state: present

- name: Deploy example Cabify App dockerized
  copy:
    src: .
    dest: "{{ cabify_path }}"
    mode: u=rwx,g=rx,o=rx

- name: Build cabify docker image
  docker_image:
    path: "{{ cabify_path }}"
    name: cabify
    tag: "{{ cabify_app_version }}"
