---
- name: Start Cabify app containers
  docker_container:
    state: started
    name: "cabify-{{ item }}"
    image: "cabify:{{ cabify_app_version }}"
    restart_policy: "on-failure"
  with_sequence: count="{{ app_replicas }}"
  when: image_shasum.changed
